### ISSUE TITLE
long comment issue

### ISSUE THREAD

**Issue by PrashantRe** [opensource-socialnetwork/opensource-socialnetwork#364]
when user enter long comment,its look like image below.
I think,need to add word-break: break-all; in css code
<a href="http://imgur.com/fAM4UWY"><img src="http://i.imgur.com/fAM4UWY.png?1" title="source: imgur.com" /></a>

**Comment by sathish4fri** [comment]
Right . we will check it

**Comment by githubertus** [comment]
we fixed this already with posts, see
https://github.com/opensource-socialnetwork/opensource-socialnetwork/commit/cfc82031cd5f4eebcb371c0217a2da2a6d2a4f1e

**Comment by PrashantRe** [comment]
@githubertus But this is not added here>>https://github.com/opensource-socialnetwork/opensource-socialnetwork.If its added,still not working.

**Comment by githubertus** [comment]
I was just trying to give a hint which way the same issue has been solved with posts already. The fix hasn't been added to comment-text yet, that's right.

**Comment by PrashantRe** [comment]
@bishopgodsey Thanks for this fix.tested and working perfectly.
