### ISSUE TITLE
comments are not working under entity profile photo

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#467]
Comments under postings will not shown but they will written into the database.

Ossn version 3.0 dev
PHP version 5.5.24
Cache enabled
Apache version XAMPP 5.5.24
MySQL version 5.6.24

**Comment by lianglee** [comment]
Did you tried with latest development release?

**Comment by TheGameHHH** [comment]
Yes, after changes from today and before that one.

**Comment by lianglee** [comment]
Can you share your website link? did you tried on fresh installation? i tried on 2 new fresh installation and its working fine. Please test on fresh installation and if issue exists , reopen this ticket,

**Comment by TheGameHHH** [comment]
Now i tried it 4 times. 2 times I did it on old installation and 2 times on new one. it didn't went at me in chrome and microsoft edge. 2 times I had the cache of ossn active and 2 times not.

**Comment by lianglee** [comment]
comments are not working under entity profile photo

**Comment by lianglee** [comment]
You have not mentioned that your comments are working under the posts that says 'Changed profile picture', next time please mention more details.

It has been fixed now.

**Comment by TheGameHHH** [comment]
it still doesn't working after new installation of today's updates. this time with xampp version 5.5.27

**Comment by lianglee** [comment]
Try again please

**Comment by TheGameHHH** [comment]
my steps, what I did
create new local domain,
create new database,
installed ossn

my proof
![unbenannt](https://cloud.githubusercontent.com/assets/5566418/8966205/5be20eb6-3630-11e5-88c1-8c72b97b55ce.JPG)

**Comment by TheGameHHH** [comment]
thanks, after latest update it works now.
